### ISSUE TITLE
Run-time option to generate BIRD compatible output?

### ISSUE THREAD

**Issue by robert-scheck** [kristapsdz/rpki-client#10]
Do you have plans to add a run-time option (e.g. command line argument for `rpki-client`) in order to generate BIRD compatible output rather just for OpenBGPD? I would of course try to deliver the BIRD specific code, but a general switch option would be needed first.

**Comment by kristapsdz** [comment]
Yes, from OpenBSD I'm merging BIRD, CSV, and JSON (alongside the original bgpd) output code.

**Comment by kristapsdz** [comment]
Just checked in.  JSON and CSV are on the way.
