### ISSUE TITLE
Support for BIRD 2.x format

### ISSUE THREAD

**Issue by robert-scheck** [kristapsdz/rpki-client#20]
Currently, rpki-client supports only BIRD 1.x format, while BIRD 1.x is maintenance-only at upstream and doesn't receive any new features, too. Unfortunately, BIRD 2.x has another format.

**Comment by robert-scheck** [comment]
https://bird.network.cz/pipermail/bird-users/2020-February/014259.html provides a full configuration example with some upstream comments and clarifications.

Based on that, I've written #21, however a proper integration into `rpki-client` is missing, because:

I'm not sure if the current options `-B`, `-c`, `-j` and `-o` are _that_ great, maybe something like `-o <bird|bird2|csv|json|openbgpd>` would be more powerful and more flexible?

**Comment by job** [comment]
It is probably best to discuss this with the upstream via the
tech@openbsd.org mailing list.

The intention of this repository is to be a portable version of what
lives in the openbsd tree.

**Comment by robert-scheck** [comment]
Done: https://marc.info/?l=openbsd-tech&m=158319525301052&w=2

**Comment by robert-scheck** [comment]
Adressed in OpenBSD: https://marc.info/?l=openbsd-tech&m=158351373204997&w=2

**Comment by kristapsdz** [comment]
This should be fixed now!
