### ISSUE TITLE
BIRD 1.x output format broken?

### ISSUE THREAD

**Issue by robert-scheck** [kristapsdz/rpki-client#23]
As of writing, the output format of `rpki-client` for `-B` (BIRD 1.x) looks like this:

```
roa table roa {
  roa 1.0.0.0/24 max 24 as 13335;
  # […]
  roa 2001:200::/32 max 32 as 2500;
  # […]
}
```
As per [upstream's confirmation](http://trubka.network.cz/pipermail/bird-users/2020-February/014275.html) this combined format can't be used with BIRD 1.x as-is, it needs to be splitted into separate files for IPv4 and IPv6 which can be used separately for `bird` respectively `bird6`.

This raises the question if the currently in `rpki-client` implemented BIRD 1.x output format is broken? Or am I still overlooking something?

**Comment by job** [comment]
good point, perhaps when -B is called, we should generate 3 files:=

bird1-ipv6
bird1-ipv4
bird2

and people can use whatever they need for their environment

**Comment by robert-scheck** [comment]
In https://github.com/kristapsdz/rpki-client/issues/20#issuecomment-591693200, I also proposed other possible command-line options (just to mention it here as well). Maybe upstream (you? @kristapsdz?) can make a decision? If my non-extensive C knowledge allows it, I'll then try to provide an updated PR.

**Comment by kristapsdz** [comment]
I think @cjeker can probably provide some input to this and the bird2 question.  Claudio?

**Comment by robert-scheck** [comment]
Adressed in OpenBSD: https://marc.info/?l=openbsd-tech&m=158351373204997&w=2

**Comment by kristapsdz** [comment]
Robert, I'll be synchronising the repository with OpenBSD's downstream over the next few days!

**Comment by kristapsdz** [comment]
This should be fixed now!
